/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.mainClass;

/**
 *
 * @author asus
 */
public class cekGudang extends javax.swing.JFrame {

    /**
     * Creates new form keluarGudang
     */
    public cekGudang() {
        initComponents();


        txtCariCek.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleScannedCode(txtCariCek.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtCariCek = new javax.swing.JTextField();
        btnCariCek = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblDataCek = new javax.swing.JTable();
        btnKembaliCek = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CEK PRODUK");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(28, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(26, 26, 26))
        );

        txtCariCek.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtCariCekComponentAdded(evt);
            }
        });
        txtCariCek.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCariCekFocusGained(evt);
            }
        });
        txtCariCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariCekActionPerformed(evt);
            }
        });

        btnCariCek.setText("CARI");
        btnCariCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariCekActionPerformed(evt);
            }
        });

        tblDataCek.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Produk", "Nama Produk", "Harga", "Stok"
            }
        ));
        jScrollPane1.setViewportView(tblDataCek);

        btnKembaliCek.setText("<-- KEMBALI");
        btnKembaliCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliCekActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnKembaliCek)
                .addGap(100, 100, 100)
                .addComponent(txtCariCek, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCariCek)
                .addContainerGap(165, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariCek, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCariCek)
                    .addComponent(btnKembaliCek))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariCekActionPerformed
        // TODO add your handling code here:
        try {
            String kodeProdukToSearchCek = txtCariCek.getText();

            if (kodeProdukToSearchCek.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan isi Kode Produk terlebih dahulu");
            } else {
                // Panggil metode searchByKodeProduk untuk menampilkan hasil pencarian pada tabel
                cariByKodeProdukCek(kodeProdukToSearchCek);
            }
        } catch (HeadlessException | NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariCekActionPerformed

    private void btnKembaliCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliCekActionPerformed
        // TODO add your handling code here:
        this.dispose();

        menu appmenu = new menu();
        appmenu.setVisible(true);
    }//GEN-LAST:event_btnKembaliCekActionPerformed

    private void txtCariCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariCekActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariCekActionPerformed

    private void txtCariCekFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCariCekFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariCekFocusGained

    private void txtCariCekComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtCariCekComponentAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariCekComponentAdded

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cekGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cekGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cekGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cekGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cekGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCariCek;
    private javax.swing.JButton btnKembaliCek;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblDataCek;
    private javax.swing.JTextField txtCariCek;
    // End of variables declaration//GEN-END:variables

    private void cariByKodeProdukCek(String kodeProduk) {
        try {
            String where = " WHERE kode_produk = '" + kodeProduk + "'";

            Object[] tabel = {"Kode Produk", "Nama Produk", "Harga", "Stok"};
            DefaultTableModel model = new DefaultTableModel(null, tabel);
            tblDataCek.setModel(model);

            Connection c = mainClass.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM data_produk " + where;
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                String kode_produk = rs.getString("kode_produk");
                String nama_produk = rs.getString("nama_produk");
                String harga = rs.getString("harga");
                String stok = rs.getString("stok");

                Object[] data = {kode_produk, nama_produk, harga, stok};
                model.addRow(data);
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }

    }
    
    private void handleScannedCode(String scannedCode) {
    try {
        String where = " WHERE kode_produk = '" + scannedCode + "'";

        Object[] tabel = {"Kode Produk", "Nama Produk", "Harga", "Stok"};
        DefaultTableModel model = new DefaultTableModel(null, tabel);
        tblDataCek.setModel(model);

        Connection c = mainClass.sambungkeDB();
        Statement st = c.createStatement();
        String sql = "SELECT * FROM data_produk " + where;
        ResultSet rs = st.executeQuery(sql);

        while (rs.next()) {
            String kode_produk = rs.getString("kode_produk");
            String nama_produk = rs.getString("nama_produk");
            String harga = rs.getString("harga");
            String stok = rs.getString("stok");

            Object[] data = {kode_produk, nama_produk, harga, stok};
            model.addRow(data);
        }
    } catch (SQLException ex) {
        JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
    }
    
    }
}
