/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

import javax.swing.JOptionPane;


/**
 *
 * @author asus
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        btnMenuInput = new javax.swing.JButton();
        btnMenuCek = new javax.swing.JButton();
        btnMenuLogout = new javax.swing.JButton();
        lblNama = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("MENU APLIKASI GUDANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel2)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("SELAMAT DATANG");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 100, -1, -1));

        btnMenuInput.setBackground(new java.awt.Color(204, 204, 204));
        btnMenuInput.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMenuInput.setText("INPUT PRODUK");
        btnMenuInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuInputActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuInput, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 160, -1, 50));

        btnMenuCek.setBackground(new java.awt.Color(204, 204, 204));
        btnMenuCek.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnMenuCek.setText("CEK PRODUK");
        btnMenuCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuCekActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuCek, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 160, 128, 50));

        btnMenuLogout.setText("LOGOUT");
        btnMenuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuLogoutActionPerformed(evt);
            }
        });
        getContentPane().add(btnMenuLogout, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));

        lblNama.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblNama.setText("-------");
        getContentPane().add(lblNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 70, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMenuInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuInputActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        newGudang formGudang = new newGudang();
        formGudang.setVisible(true);
    }//GEN-LAST:event_btnMenuInputActionPerformed

    public void updateNamaLabel(String username) {
        lblNama.setText(username);
    }
    
    private void btnMenuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuLogoutActionPerformed
        // TODO add your handling code here:
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Kamu yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            
            Login formLogin = new Login();
            formLogin.setVisible(true);
            
            System.exit(0);
        }
    }//GEN-LAST:event_btnMenuLogoutActionPerformed

    private void btnMenuCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuCekActionPerformed
        // TODO add your handling code here:
        this.dispose();
        
        cekGudang formCek = new cekGudang();
        formCek.setVisible(true);
    }//GEN-LAST:event_btnMenuCekActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMenuCek;
    private javax.swing.JButton btnMenuInput;
    private javax.swing.JButton btnMenuLogout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblNama;
    // End of variables declaration//GEN-END:variables

   
}
