/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package apps;

import java.awt.HeadlessException;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import main.mainClass;

/**
 *
 * @author asus
 */
public class newGudang extends javax.swing.JFrame {

    /**
     * Creates new form newGudang
     */
    public newGudang() {
        initComponents();
        displayDataP("");

        txtCariP.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                handleScannedCode(txtCariP.getText());
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtCari = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblDataCari = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        txtKp = new javax.swing.JTextField();
        txtNp = new javax.swing.JTextField();
        txtHs = new javax.swing.JTextField();
        txtStok = new javax.swing.JTextField();
        cmbKat = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblData = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnDelet = new javax.swing.JButton();
        txtCariP = new javax.swing.JTextField();
        btnLogoutM = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        lblNamaM = new javax.swing.JLabel();
        btnResetP = new javax.swing.JButton();

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Kode Produk");

        txtCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnCari.setBackground(new java.awt.Color(51, 102, 255));
        btnCari.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnCari.setForeground(new java.awt.Color(255, 255, 255));
        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        tblDataCari.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(tblDataCari);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCari)
                .addContainerGap(714, Short.MAX_VALUE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(47, 47, 47)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addGap(131, 131, 131))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("APLIKASI INVENTORY GUDANG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jLabel2.setText("ID Produk");

        jLabel3.setText("Kode Produk");

        jLabel4.setText("Nama Produk");

        jLabel5.setText("Kategori");

        jLabel6.setText("Harga");

        jLabel7.setText("Stok");

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });

        txtKp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtKpKeyTyped(evt);
            }
        });

        txtHs.setText("Rp.");

        txtStok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStokActionPerformed(evt);
            }
        });

        cmbKat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Makanan", "Minuman", "Sembako", "MCK" }));

        tblData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblData);

        btnSave.setBackground(new java.awt.Color(51, 153, 255));
        btnSave.setText("SIMPAN");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnEdit.setBackground(new java.awt.Color(102, 255, 102));
        btnEdit.setText("EDIT");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnDelet.setBackground(new java.awt.Color(255, 51, 51));
        btnDelet.setText("HAPUS");
        btnDelet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeletActionPerformed(evt);
            }
        });

        txtCariP.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtCariPKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCariPKeyTyped(evt);
            }
        });

        btnLogoutM.setBackground(new java.awt.Color(204, 204, 204));
        btnLogoutM.setText("LOGOUT");
        btnLogoutM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutMActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("HELLO");

        lblNamaM.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNamaM.setText("--------");

        btnResetP.setText("RESET");
        btnResetP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetPActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtNp)
                                    .addComponent(txtId)
                                    .addComponent(txtKp)
                                    .addComponent(cmbKat, 0, 130, Short.MAX_VALUE)
                                    .addComponent(txtHs)
                                    .addComponent(txtStok))
                                .addGap(41, 41, 41))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(btnSave)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnEdit)
                                        .addGap(18, 18, 18)
                                        .addComponent(btnDelet))
                                    .addComponent(btnLogoutM))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblNamaM, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnResetP)
                        .addGap(27, 27, 27)
                        .addComponent(txtCariP, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCariP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(lblNamaM)
                    .addComponent(btnResetP))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(txtKp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbKat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtHs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnSave)
                            .addComponent(btnEdit)
                            .addComponent(btnDelet))
                        .addGap(58, 58, 58)
                        .addComponent(btnLogoutM))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(951, 951, 951)
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtStokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStokActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtStokActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        try {
            String id_produk = txtId.getText();
            String kode_produk = txtKp.getText();
            String nama_produk = txtNp.getText();
            String kategori = cmbKat.getSelectedItem().toString();
            String harga = txtHs.getText();
            String stok = txtStok.getText();

            // Memeriksaan kode_produk sudah digunakan
            String checkDuplicateSql = "SELECT COUNT(*) FROM data_produk WHERE kode_produk = '" + kode_produk + "'";
            Connection connection = mainClass.sambungkeDB();
            Statement checkDuplicateStatement = connection.createStatement();
            ResultSet resultSet = checkDuplicateStatement.executeQuery(checkDuplicateSql);
            resultSet.next();
            int count = resultSet.getInt(1);

            if (count > 0) {
                // Jika Kode produk sudah ada, tampilkan pesan kesalahan
                JOptionPane.showMessageDialog(this, "Kode Produk sudah ada. Silakan gunakan kode yang berbeda.");

            } else if (id_produk.isEmpty() || kode_produk.isEmpty() || nama_produk.isEmpty() || kategori.isEmpty() || harga.isEmpty() || stok.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan Isi Data Produk Dahulu Mas.....!!!");

            } else {
                // Jika Kode produk belum ada, lakukan operasi INSERT
                String insertSql = "INSERT INTO data_produk"
                        + "(`id_produk`, `kode_produk`, `nama_produk`, `kategori`, `harga`, `stok`)"
                        + "VALUES "
                        + "("
                        + "'" + id_produk + "',"
                        + "'" + kode_produk + "',"
                        + "'" + nama_produk + "',"
                        + "'" + kategori + "',"
                        + "'" + harga + "',"
                        + "'" + stok + "'"
                        + ")";
                System.out.println(insertSql);

                // Lanjutkan dengan eksekusi query INSERT
                Statement insertStatement = connection.createStatement();
                insertStatement.executeUpdate(insertSql);
                newGudang.displayDataP("");
                JOptionPane.showMessageDialog(this, "Data Berhasil ditambah ke DataBase!!");

                // Mengosongkan semua JTextField
                txtId.setText("");
                txtKp.setText("");
                txtNp.setText("");
                cmbKat.setSelectedIndex(0);
                txtHs.setText("Rp.");
                txtStok.setText("");
            }

        } catch (HeadlessException | NumberFormatException | SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Ditambah Mas!!! \n" + e.getMessage());
        }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnCariActionPerformed

    private void btnDeletActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeletActionPerformed
        // TODO add your handling code here:
        try {
            int selectedRow = tblData.getSelectedRow();
            if (selectedRow != -1) {
                String idToDelete = tblData.getValueAt(selectedRow, 0).toString();

                String sqlDelete = "DELETE FROM data_produk WHERE id_produk = '" + idToDelete + "'";

                Connection c = mainClass.sambungkeDB();
                Statement st = c.createStatement();
                st.executeUpdate(sqlDelete);
                displayDataP("");

                JOptionPane.showMessageDialog(this, "Data Berhsil Dihapus dari DataBase!!");
            } else {
                JOptionPane.showMessageDialog(this, "Silahkan Pilih Baris untuk Dihapus!!");
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Data Gagal Dihapus!! \n" + e.getMessage());
        }

    }//GEN-LAST:event_btnDeletActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int selectedRow = tblData.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris untuk diedit.");
            return;
        }

        //Ambil nilai baris terpilih
        String id_produk = tblData.getValueAt(selectedRow, 0).toString();
        String kode_produk = tblData.getValueAt(selectedRow, 1).toString();
        String nama_produk = tblData.getValueAt(selectedRow, 2).toString();
        String kategori = tblData.getValueAt(selectedRow, 3).toString();
        String harga = tblData.getValueAt(selectedRow, 4).toString();
        String stok = tblData.getValueAt(selectedRow, 5).toString();

        // Tampilkan formulir pengeditan
        EditFormP editForm = new EditFormP(id_produk, kode_produk, nama_produk, kategori, harga, stok);
        editForm.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnLogoutMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutMActionPerformed
        // TODO add your handling code here:

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Kamu yakin ingin Keluar?", "Konfirmasi Keluar", JOptionPane.YES_NO_OPTION);

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();

            Login formLogin = new Login();
            formLogin.setVisible(true);

            System.exit(0);
        }

    }//GEN-LAST:event_btnLogoutMActionPerformed

    public void updateNamaLabel(String username) {
        lblNamaM.setText(username);
    }

    private void txtKpKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtKpKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKpKeyTyped

    private void txtCariPKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariPKeyTyped

    private void txtCariPKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCariPKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariPKeyReleased

    private void btnResetPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetPActionPerformed
        // TODO add your handling code here:
        displayDataP("");
    }//GEN-LAST:event_btnResetPActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(newGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(newGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(newGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(newGudang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new newGudang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnDelet;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnLogoutM;
    private javax.swing.JButton btnResetP;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbKat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lblNamaM;
    public static javax.swing.JTable tblData;
    private javax.swing.JTable tblDataCari;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtCariP;
    private javax.swing.JTextField txtHs;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtKp;
    private javax.swing.JTextField txtNp;
    private javax.swing.JTextField txtStok;
    // End of variables declaration//GEN-END:variables

    public static void displayDataP(String where) {
        Object[] tabel = {"ID", "Kode Produk", "Nama Produk", "Kategori", "Harga", "Stok"};
        DefaultTableModel model = new DefaultTableModel(null, tabel);
        tblData.setModel(model);
        try {
            Connection c = mainClass.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM data_produk " + where;
            ResultSet rs = st.executeQuery(sql);
            while (rs.next()) {
                String id_produk = rs.getString("id_produk");
                String kode_produk = rs.getString("kode_produk");
                String nama_produk = rs.getString("nama_produk");
                String kategori = rs.getString("kategori");
                String harga_satuan = rs.getString("harga");
                String stok = rs.getString("stok");
                Object[] data = {id_produk, kode_produk, nama_produk, kategori, harga_satuan, stok};
                model.addRow(data);
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
    }

    private void handleScannedCode(String scannedCode) {
        try {
            if (scannedCode.isEmpty()) {
                JOptionPane.showMessageDialog(this, "Silahkan Masukan Kode Produk Terlebih Dahulu!", "Peringatan", JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            String where = " WHERE kode_produk = '" + scannedCode + "'";

            Object[] tabel = {"ID", "Kode Produk", "Nama Produk", "Kategori", "Harga", "Stok"};
            DefaultTableModel model = new DefaultTableModel(null, tabel);
            tblData.setModel(model);

            Connection c = mainClass.sambungkeDB();
            Statement st = c.createStatement();
            String sql = "SELECT * FROM data_produk " + where;
            ResultSet rs = st.executeQuery(sql);
            
            boolean found = false;

            while (rs.next()) {
                String id_produk = rs.getString("id_produk");
                String kode_produk = rs.getString("kode_produk");
                String nama_produk = rs.getString("nama_produk");
                String kategori = rs.getString("kategori");
                String harga_satuan = rs.getString("harga");
                String stok = rs.getString("stok");

                Object[] data = {id_produk, kode_produk, nama_produk, kategori, harga_satuan, stok};
                model.addRow(data);
                found = true;
            }
            
            if (!found) {
                JOptionPane.showMessageDialog(this, "Produk dengan kode " + scannedCode + " tidak ditemukan.", "Informasi", JOptionPane.INFORMATION_MESSAGE);
                
                displayDataP("");
            }

            txtCariP.setText("");

        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }

    }

}
